name: Pulumi Deploy with OIDC

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

# 1. Required permissions for OIDC
permissions:
  id-token: write   # Enables GitHub OIDC token
  contents: read    # For code checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 2. Configure AWS credentials via OIDC (no secrets needed!)
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::904233128713:role/pulumi-oidc-role
          aws-region: us-east-1

      # 3. Pulumi deployment
      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_ESC_ENVIRONMENT: Girisha/assign/aws-oidc 
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pulumi/actions@v4
      with:
        command: up
        stack-name: dev
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
